### PR TITLE
Fix database migration on plugin updates

### LINKED ISSUE #1: Plugin update does not run database migration
If updating the plugin, the database migrations are only run if the plugin is deactivated and activated again. The database migrations should run automatically after a plugin upgrade instead.

### PR DESCRIPTION
**Pull request by prab18hat**
Previously, database migrations only ran during plugin activation, causing issues when users updated the plugin. This fix adds automatic version checking that runs database migrations whenever needed.

Resolves #1

### CODE REVIEW

**Comment by prab18hat** [comment]
Kindly check this PR ?

**Review by steff-mueller — CHANGES_REQUESTED** [review]

File: wp-mux-livestream.php [hunk 1]
```diff
@@ -18,17 +18,33 @@
...
+
+/**
+ * Check if database schema needs to be updated.
+ */
+function check_database_version() {
+	$installed_db_version = get_option( 'wp_mux_livestream_db_version' );
+	
+	if ( $installed_db_version !== WP_MUX_LIVESTREAM_DB_VERSION ) {
+		create_db_table();
+		update_option( 'wp_mux_livestream_db_version', WP_MUX_LIVESTREAM_DB_VERSION );
```
Comment (steff-mueller) [inline wp-mux-livestream.php:45]:
```suggestion
```
